# Generated by Django 3.0.7 on 2020-06-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetmodel',
            options={'managed': False},
        ),
    ]
