# Generated by Django 3.0.7 on 2020-06-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterweb', '0002_auto_20200614_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetmodel',
            options={'managed': True},
        ),
    ]
