# Generated by Django 3.0.7 on 2020-06-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterweb', '0004_tweetmodel_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetmodel',
            options={},
        ),
    ]
