# Generated by Django 3.0.7 on 2020-07-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterweb', '0005_auto_20200628_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTermModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
            ],
        ),
    ]
